# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric properties
common_minecraft_version = 26.1
loader_version = 0.19.3
loom_version = 1.17-SNAPSHOT

# Mod properties
mod_version = 2.0.0
maven_group = me.mightyknight
archives_base_name = shield-disruptor

# Other
common_modmenu_version = 18.0.0-beta.1
common_cloth_config_version = 26.1.154
fabric_shield_lib_version=
mixin_extras_version=0.5.4
maven_artifact=3.9.11